#!/bin/bash 
COUNTER=1
declare -a DUINOS=(0,0,0,0,0,0);

while [  $COUNTER -lt 7 ]; do
    echo The counter is $COUNTER
    sudo ./ping -d $COUNTER -t 1
    if [ $? -eq 0 ]; then
        DUINOS[$COUNTER - 1]=1;
        echo 'yay'
    fi
    let COUNTER=COUNTER+1 
done
