#!/bin/bash 
COUNTER=1
while [  $COUNTER -lt 7 ]; do
    echo The counter is $COUNTER
    sudo ./ping -d $COUNTER -t 1
    if [ $? -eq 1 ]; then
        echo 'yay'
    fi
    let COUNTER=COUNTER+1 
done
