#!/bin/bash 
COUNTER=1
declare -a DUINOS=(1,1,1,1,1,1);

while [  $COUNTER -lt 7 ]; do
    echo The counter is $COUNTER
    sudo ./ping -d $COUNTER -t 1
    if [ $? -ne 0 ]; then
        INDEX=COUNTER-1;
        DUINOS[$INDEX]=0;
        echo 'yay'
    fi
    let COUNTER=COUNTER+1 
done

echo ${DUINOS[@]}